# Generated by Django 4.2 on 2023-04-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_id', models.IntegerField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('tracking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=-1, max_length=32)),
                ('status', models.CharField(choices=[('unready', 'UNREADY'), ('wait_pick', 'WAIT_PICK'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED')], default='unready', max_length=32)),
                ('truck_id', models.IntegerField(max_length=50, null=True)),
                ('deliver_x', models.IntegerField(max_length=20)),
                ('deliver_y', models.IntegerField(max_length=20)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('count', models.IntegerField(max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seqnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.IntegerField(default=0)),
                ('massege_type', models.CharField(choices=[('ugopickup', 'UGOPICKUP'), ('ugodeliver', 'UGODELIVER'), ('uquery', 'UQUERY'), ('upsamazoninitship', 'UPSAMAZONINITSHIP'), ('upsamazonstartship', 'UPSAMAZONSTARTSHIP'), ('upsamazonfinishship', 'UPSAMAZONFINISHSHIP')], max_length=254)),
                ('truck_id', models.IntegerField(default=-1)),
                ('package_id', models.IntegerField(default=-1)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(max_length=20)),
                ('y', models.IntegerField(max_length=20)),
                ('package_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('idle', 'IDLE'), ('traveling', 'TRAVELING'), ('arrive', 'ARRIVE'), ('loading', 'LOADING'), ('delivering', 'DELIVERING')], default='idle', max_length=32)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WareBindTruck',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_id', models.IntegerField()),
                ('truck_id', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(max_length=20)),
                ('y', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_id', models.IntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
